---
- name: Install Grafana on RedHat/Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Add Grafana repository
      when: ansible_os_family == 'RedHat'
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://packagecloud.io/grafana/stable/el/7/$basearch
        gpgcheck: no
        enabled: yes

    - name: Add Grafana repository
      when: ansible_os_family == 'Debian'
      apt_repository:
        repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main
        state: present

    - name: Install Grafana
      package:
        name: grafana
        state: latest

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes