---
- name: Install LAMP Server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt: name=apache2 state=latest
    - name: Install MySQL
      apt: name=mysql-server state=latest
    - name: Install PHP
      apt: name=php state=latest
    - name: Start Apache Service
      service: name=apache2 state=started enabled=yes
    - name: Start MySQL Service
      service: name=mysql state=started enabled=yes